#ifndef GLOBALVARIABLES_H
#define GLOBALVARIABLES_H

#define SCREEN_WIDTH 500
#define SCREEN_HEIGHT 500

#define PLAYER_WIDTH 50
#define PLAYER_HEIGHT 50
#define PLAYER_START_POSITION_X 0
#define PLAYER_START_POSITION_Y SCREEN_HEIGHT
#define PLAYER_INDENT_FROM_BUTTOM 1
#define PLAYER_SPEED 15

#define BULLET_HEIGHT 10
#define BULLET_WIDTH 5
#define BULLET_SPEED 5

#define ENEMY_WIDTH 50
#define ENEMY_HEIGHT 50
#define ENEMY_SPEED 5

#define HEART_WIDTH 25
#define HEART_HEIGHT 25
#define HEART_SPEED 5

#endif // GLOBALVARIABLES_H
